const int FULL_POWER = 127;
const int BASE_TIME = 1000;
const int BASE_DIST = 573;
const float BASE_ROTATION = 2.76;
const int THRESHOLD = 10;
const int Line_THRESHOLD = 2875;
task emergency_stop();
task startBot();
task joydrive();
task display();
task main();
